tobac/analysis.py, tobac/tracking.py
Merge in two commits from devlopment branch that still existed, will work on my own fork in the future
=> Merge in changes from development branch to delete that one

tobac/themes/tobac_v1/feature_detection.py
The current method of `remove_parents` is iterating each dict and embedded items. This is quite slow for large datasets.
https://github.com/climate-processes/tobac/blob/fbee1974ef97cbfbfe4b5aaf29e477e6565496b3/tobac/themes/tobac_v1/feature_detection.py#L479-L484
I have asked the question on [stack overflow](https://stackoverflow.com/questions/65986807/get-the-key-value-if-the-list-element-in-two-dicts-shares-any-tuple) and tested the accepted answer.
It improves a lot! The detailed tests are listed in the comments below ...
=> Speed up remove_parents function

tobac/segmentation.py
The location of watershed within skimage submodules changes with v0.19, but I've kept both for backward compatibility for now using a try/except statement
=> Handle import error due to changes in skimage

tobac/tracking.py
As discussed a few times in different presentations, we have sped up tracking substantially (and made it scale linearly). A simple comparison, tracking on a single day of GOES-16 IR data on a modern server processor can be seen here:
Essentially, the theme of the changes was to remove any nested loops, reducing our post-`trackpy` time complexity to O(N) rather than the O(N^2) that it was before. Where loops are necessary, I've tried to use `np.vectorize` to at least allow the loops to be vectorized. 
Longer-term, I'd like to do another PR to clean up some of the older code in this module. For example, `fill_gaps` doesn't
seem to be used in any tobac version, and is a good candidate for removal.
=> Added tracking speedups

tobac/segmentation.py, tobac/testing.py, tobac/tests/test_segmentation.py
Resolves #91 and adds new tests to our segmentation function to ensure that `level` limits the vertical levels that are seeded when using columnar seeding in segmentation.
=> Fixed `level` parameter in segmentation to work and added segmentation tests

tobac/feature_detection.py, tobac/utils.py
Similar to #89, these are our speedups to feature detection. These changes are overall a bit more complicated and the result less dramatic than #89, but these changes still provide about a 100x speedup vs. the current `main` and `dev` branches and a ~2x speedup vs `v2.0-dev`. This again shows a benchmark, using the same machine and dataset as #89: 
`feature_position`
Switched this code to use a subset of the input track data rather than performing operations on the array every time. This is particularly important for large arrays (and will be more important when 3D feature detection is added)
`remove_parents` 
Entirely new function that operates on 1D coordinates rather than 2D tuples, as that is substantially less computationally expensive. Required changes to …
=> Feature Detection Speedups

.pre-commit-config.yaml, CONTRIBUTING.md, conda-requirements.txt
Fulfills issue #82  
Also adds pre-commit to required packages for conda install (from source only)
=> Set up pre-commit for black formatting

examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb, examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb, examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb, examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb, tobac/feature_detection.py, tobac/tests/test_feature_detection.py, tobac/tests/test_sample_data.py, tobac/tracking.py
Issues #67 and #63 raised times in which duplicate or redundant parameters are used in feature detection and tracking. This PR adds future warnings for two parameters that are to be depreciated in future (min_num in feature detection and d_min in tracking) and adds an exception if multiple conflicting parameters are used. Example notebooks and tests have been updated to stop using depreciated parameters.
=> Parameter warnings

tobac/feature_detection.py, tobac/tests/test_testing.py, tobac/tests/test_tracking.py
Resolves #108 and #101. New warnings summary is below. Note that the warnings are either upstream in trackpy or iris-related, which I don't think we want to deal with. 
```
================================================== warnings summary ===================================================
tobac/tests/test_sample_data.py::test_sample_data
C:\Users\sfreeman\miniconda3\envs\tobac_dev\lib\site-packages\iris\coords.py:1982: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for 'time'.
warnings.warn(msg.format(self.name()))
tobac/tests/test_sample_data.py::test_sample_data
C:\Users\sfreeman\miniconda3\envs\tobac_dev\lib\site-packages\iris\coords.py:1982: UserWarning: Collapsing a non-contiguous coordinate. Metadata may not be fully descriptive for …
```
=> Fix depreciation warnings that we can fix

tobac/plotting.py
Resolves #95.
@w-k-jones I think there's a chance that this could potentially break some code. For example, if a user tries to run `tobac.plotting.plot_tracks_mask_field_loop` in a script without setting their own backend, it could break. We could resolve it by putting the matplotlib imports into each function and setting `mpl.use('agg')` there, but I still think we're better off having the users set their own backend as `agg` isn't appropriate for all cases.
=> Remove setting backend to `agg` automatically

tobac/utils/general.py
I updated `get_spacings()` in `utils/general.py` because previously this function assumed that for datasets with lon-lat coordinates, these were two-dimensional with 'lon' being the first dimension and 'lat' being the second dimension. I mistakenly introduced this with #65, and I think it is better to make the function more general so that it works for both 1D and 2D lat and lons and independent of their dimension order.
=> updated get_spacings() to calculate dxy from 1D or 2D lat-lon values, independent of their dimension order 

tobac/plotting.py
This resolves #128 and #121, related to the fact that `map_tracks` in the plotting module depends on the untracked cells being labeled as `np.nan`.
Given the number of bug reports related to this, I recommend that we release this as a hotfix 1.3.1 release.
=> Fix `map_tracks` with untracked cell number change

CHANGELOG.md, setup.py
Resolves the first two parts of #141 and gets us ready for a release.
=> Version bump and changelog addition

tobac/segmentation.py
This resolves #145 and calls for the `segmentation_2D` and `segmentation_3D` to be removed by v1.5.0.
=> Added depreciation warnings to two segmentation functions

tobac/feature_detection.py, tobac/tests/test_feature_detection.py
This PR addresses #148 and resolves a bug when using `weighted_abs` feature position in 1.3.x. Given the hotfix nature of this, I'm suggesting we stage it for a relatively rapidly released 1.3.2.
=> Fixing `weighted_abs` feature position

.github/workflows/check_formatting.yml, CONTRIBUTING.md
This PR specifies the version of `black` we use to check formatting.
Should resolve #160.
=> Use a specified version of black in workflow

tobac/tests/test_tracking.py, tobac/tracking.py
This PR aims at solving #169 temporarily by implementing two workarounds for problems upstream in trackpys predictive tracking in `linking_trackpy()`:
1. Switching to `link_df_iter` from `link_df` since the latter method isn't working correctly.
2. Avoiding to set `pos_columns` in `link_df_iter`, because this causes incorrect tracking.
The issue in trackpy for reference: https://github.com/soft-matter/trackpy/issues/699
Furthermore a test to check whether prediction works correctly is added
not needed:
=> Implementing Workarounds and Test for method='prediction'

tobac/tests/test_tracking.py, tobac/tracking.py
Resolves the first part of #165 by raising a `NotImplementedError` when users try to use extrapolation.
=> Raise NotImplementedError when using extrapolation

doc/big_datasets.rst, doc/index.rst, tobac/tests/test_utils.py, tobac/utils.py
This should address #17 (!) and provides a function for combining multiple, independently identified feature dataframes into a single dataframe appropriate for tracking.
=> New function to combine feature dataframes

tobac/feature_detection.py, tobac/tests/test_feature_detection.py
The feature detection does currently not work when  `min_distance` is not 0. An exception is raised in `filter_min_distance()` , because the input feature dataframe for this function can contain index values that are double-defined as a consequence of  concatenating dataframes in `feature_detection_multithreshold_timestep()`. This PR solves #184 by assuring that the feature dataframe that is created in `feature_detection_multithreshold_timestep()` gets unique indices. 
I also added a test for  `filter_min_distance()` to test if features are removed as expected within a specified minimum distance and I removed redundant imports from `test_feature_detection.py`.
=> Bug fix: Assure that feature dataframe indices are unique

.gitignore, README.md, setup.py, tobac/__init__.py
Resolves the first half of #185. Rather than dropping support for <3.7, I'm proposing that we only deprecate it in the code. We will still tell conda-forge that we require >=3.7, but this allows users who must remain on old versions to stick around for now. We will drop support with v1.5, as I'd really like to start adding typing annotations.
=> Deprecate Python 3.6 and lower support

README.md
This will resolve #58 and also contains more general updates to our `README`, including changing URLs and updating our contributing section.
=> Updates to `README.md`

tobac/centerofgravity.py, tobac/plotting.py, tobac/wrapper.py
This PR is simply to add several DeprecationWarnings to various functions that have been discussed before as needing to be removed or substantially reworked for v2.0. Getting these DeprecationWarnings into v1.5 should give users enough time to migrate away from the functions. 
Resolves #198 and #158.
=> Add DeprecationWarnings to several old functions

tobac/analysis.py
As discussed in #146 (and similar to #200), this deprecates three functions in `analysis.py`: `cell_statistics_all`, `cell_statistics`, and `cog_cell`. These functions likely don't work and should be reworked in any event before 2.0.
=> Deprecate some analysis functions

tobac/tests/test_feature_detection.py, tobac/tests/test_tracking.py, tobac/tracking.py
New tests have been added to check that the column names in feature detection mirror the names of the coords in the input data. Existing tests for tracking have been added to ensure that the column names of the tracking dataframe matches those of the features dataframe aside from the "cell" column, and that column names are not duplicated.
Tracking has also been modified to overwrite the features dataframe with a copy to prevent modifications to the input dataframe, and the temporary column names for the predictive tracking workaround have been further obfuscated to avoid any likely conflict with other column names.
=> Add tests for column names in feature detection and tracking

tobac/tests/test_tracking.py, tobac/tracking.py
This pull request should resolve #212.
A simple check has been added to correctly handle the case of neither `v_max, d_min, d_max` being passed to `linking_trackpy`, i.e. a `ValueError` is raised if all three arguments are missing. A corresponding test case has also been added.
=> Resolves #212

tobac/feature_detection.py, tobac/tests/test_feature_detection.py, tobac/utils.py
This PR takes the same changes made in #244 and #250 and re-implements them on v1.4 to allow for a hotfix release. The logic tree in `filter_min_distance` has been simplified based on the suggestion of @lettlini in the review of #244 
Note that `filter_min_distance` is not tested as comprehensively due to the missing tests that are implemented for v1.5
Hopefully this won't create merge conflicts for v1.5...
=> Move fixes to `filter_min_distance` and 2d coordinate interpolation to v1.4.

tobac/utils/general.py
Fixes the problem with 2d coordinate interpolation producing `object` dtypes in feature_detection raised in #240 that was the cause of the bug in #239 
Ideally this could be released as part of v1.4.2, but the changes to the utils structure as part of v1.5 make it impractical to separate
=> Fix 2d coordinate interpolation

tobac/utils/internal.py
In cases where the coordinate is no longer a dimensional coordinate (such as after slicing over that dimension), `find_axis_from_coord` would result in an IndexError (see #254). This now returns `None` in the same manner as if the coord was not found in the cube
=> Fix for `find_axis_from_coord` if the coordinate is not a dimensional coord

tobac/testing.py, tobac/tests/test_testing.py, tobac/tests/test_tracking.py, tobac/utils/general.py
I sped up `utils.general.combine_tobac_feats` several times by getting rid of `.loc` functions. Because I used the `idx` column in the new `combine_tobac_feats` function (as it is guaranteed to be output by feature detection), I had to add it to the testing generation function and fix some of the tests to expect an `idx` column.
=> Speedup `combine_tobac_feats`

tobac/tests/test_tracking.py, tobac/tracking.py
Resolves #271 and sets `time_cell` of untracked cells to `NaT`. The way that I checked for this in the tests is a bit odd, but it should avoid machine-specific issues.
=> Set `time_cell` of untracked cells to `NaT`

tobac/utils/general.py
This PR replaces all calls to `interp2d` with `interpn`. 
When conducting a review, unfortunately, caution is required in some places, as not all situations are covered by unit tests.
=> Refactor: Replace interp2d with interpn

.github/workflows/check_formatting.yml, dev_requirements.txt, doc/conf.py, example_requirements.txt, setup.py, tobac/analysis.py, tobac/plotting.py, tobac/wrapper.py
`setup.py` now finds required packages by parsing `requirements.txt`, rather than having to maintain the list of packages in both
I've also added two new requirements files -- `dev_requirements.txt` and `example_requirements.txt` that contain the additional dependencies for developers and for running the example notebooks respectively.
The `check_formatting` action previously used `pip` to install requirements, however this broke when trying to install `cartopy`. I've changed it to use `conda` instead, in the same manner as the `codecov-CI` action
=> Automatically find requirements in setup.py, add new dev and example requirement files and update check_formatting action to use conda instead of pip

.zenodo.json
Updating the author list in Zenodo to update my affiliation and re-order to the following: 
- `tobac community` first author
- Lead developers (alphabetical order by last name)
- Steering team (alphabetical order by last name)
- Original developers 
- All other contributors
There are still several contributors who should probably be on here, but I will let them add themselves. 
I removed the checklist because it's not relevant for this.
=> Update Zenodo Author Info pre-1.5

.github/workflows/check_json.yml
This is a draft Github action that checks the formatting of `.zenodo.json`.
=> feature: added github action for checking .zenodo.json formatting

CHANGELOG.md
We should start requiring PRs to update the changelog. 
This is the changelog for v1.5.0. I will be pretty aggressive in merging this given that we will have another chance to look at this when we merge `RC_v1.5.0` into `main`.
=> v1.5.0 Changelog

tobac/feature_detection.py, tobac/tests/test_feature_detection.py
Fix for the bugs identified in strict thresholding in #314 and #315 . Strict thresholding is now handled in `remove_parents`, by removing features which do not have parents, rather than by modifying the input data.
- Strict thresholding now works for `target="minimum"`
- Strict thresholding produces identical results to non-stric thresholding if `n_min_threshold` is a fixed value
- New tests added for strict thresholding
=> Reimplimentation of strict thresholding

CHANGELOG.md, doc/feature_detection/notebooks/feature_detection_filtering.ipynb, doc/feature_detection/notebooks/multiple_thresholds_example.ipynb, doc/feature_detection/notebooks/n_min_threshold_example.ipynb, doc/feature_detection/notebooks/position_threshold_example.ipynb, examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb, examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb, examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb, examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb, examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb, tobac/__init__.py
Update version number, changelog and notebooks for v1.5.1 release
=> V1.5.1 release updates

tobac/utils/__init__.py, tobac/utils/general.py
We inadvertently removed `standardize_track_dataset` when we reworked the utils functions in #191. I've added it back here to `utils/general.py`. 
I've marked this to merge with the hotfix branch, as I think it would be ideal to get this into v1.5.1. 
This resolves #329.
=> Add back `standardize_track_dataset`

.readthedocs.yml, CHANGELOG.md
Resolves an issue with readthedocs builds discovered with #335. 
We, incidentally, talked about this today. See: https://blog.readthedocs.com/drop-support-system-packages/ . While we had to deal with some of the consequences of this earlier, we now have the new issue of `system_packages: true` in our readthedocs config, breaking readthedocs builds. This PR should alleviate that issue.
In my mind, this is now a blocking PR, and 1.5.1 shouldn't be released until this is merged or the issue is resolved in some other way.
=> Fix to readthedocs builds

.github/workflows/check_notebooks.yml, CHANGELOG.md, example_requirements.txt
Resolves #339 and fixes our Jupyter Notebook CI by switching the dependency installer to `mamba` from `conda`. Also fixed a bug with our requirements that did not explicitly require `h5netcdf` which is required for the example that uses s3 to work.
=> Fix for Jupyter Notebook CI

CHANGELOG.md, tobac/utils/internal.py
Resolves #332 and handles `numba` import errors more gracefully
=> Graceful handling of Numba import errors

.github/workflows/check_notebooks.yml, .readthedocs.yml, CHANGELOG.md, doc/feature_detection/notebooks/feature_detection_filtering.ipynb, doc/feature_detection/notebooks/multiple_thresholds_example.ipynb, doc/feature_detection/notebooks/n_min_threshold_example.ipynb, doc/feature_detection/notebooks/position_threshold_example.ipynb, example_requirements.txt, examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb, examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb, examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb, examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb, examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb, tobac/__init__.py, tobac/feature_detection.py, tobac/tests/test_feature_detection.py, tobac/utils/__init__.py, tobac/utils/general.py, tobac/utils/internal.py
Hotfix v1.5.1 release for issue with strict thresholding found in #314 and #315, fixed by #316
=> Merge `RC_v1.5_hotfix` into `main`

tobac/tests/test_tracking.py
Fixes issue related to non-unique index values in dataframes for testing.
Solves #342
=> fixed duplicate index issue in test_trackpy_predict

.readthedocs.yml, doc/requirements.txt, tobac/segmentation.py, tobac/utils/periodic_boundaries.py
Fixes out-of-bounds error in segmentation due to PBC features in #349 
I also changed the location where 'column' seeding places the marker. Previously it took the floor of the array index, but now it goes to the nearest index. This may change the results of segmentation, so I can revert it if it is an issue
=> Pbc feature location fix

.github/workflows/check_formatting.yml, tobac/analysis.py, tobac/plotting.py, tobac/tests/test_segmentation.py
Coming from a frustrating experience developing #354, update our black integration to specify what it would change and also set the versions to ensure compatibility. We will need to update this file when we bump versions (on either end).
=> Update black integration to say what is wrong and fix python versions

doc/index.rst, doc/publications.rst, doc/segmentation_parameters.rst, doc/threshold_detection_parameters.rst, tobac/feature_detection.py, tobac/segmentation.py
Addresses #346 and #347. 
Note that for #346, I have only changed the documentation now, but could also update the segmentation function with an optional input parameter to make the threshold inclusive. Thoughts? 
Also, happy to get help on recent publications that I have missed. @freemansw1 maybe you are aware of additional ones for INCUS or from any CSU students that I could not find :)
=> Update references and documentation on threshold use 

.github/workflows/pylint.yml
This is testing a theory, and is entirely copied from #278 . Per the GitHub documentation (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token), the Pylint runner will never work on Julia's fork (and in #278) as the maximum access for PRs from public forked repos is read. In theory, this, which copies over the changes from #278 to a branch within our repo, *should* work.
=> Add Pylint to Workflow

tobac/tests/test_tracking.py, tobac/tracking.py
The most minor of changes to resolve #375
=> Uncomment `dist_func` parameter to enable PBCs with predictive tracking

tobac/utils/general.py
I found a bug in the get_spacing functionality and fixed it.
*Problem:* If x is storing in ascending and y in descending order (and vice versa), than the grid spacing increment subtract eachother - which is not wanted. 
*Solution:* used the absolute value
*Extension:* 
- also added a new keyword `average_type` to allow to switch between averaging strategies
- implemented geometric mean which more appropriate in my view
Cheers, Fabian.
PS: should be very easy to review and merge back
=> Bugfix in grid spacing

.github/workflows/check_formatting.yml, tobac/tests/test_convert.py, tobac/utils/bulk_statistics.py, tobac/utils/decorators.py, tobac/utils/general.py, tobac/utils/internal/basic.py
Pulls code from #354 to allow developers to specify (with a new argument to the decorator `irispandas_to_xarray`) whether or not an `iris`->`xarray` conversion occurred, via a passed keyword argument. 
Important note: I've now changed all of our decorators to allow keyword arguments. That means that when calling decorators in the future, you must call with an empty `()` regardless of whether or not you want to use them.
=> Add ability to save whether or not an `iris` to `xarray` conversion happened in the decorators

tobac/analysis.py, tobac/feature_detection.py, tobac/segmentation.py, tobac/utils/general.py
This PR fixes issues with the `RC_v1.5.x` branch caused by merging in #380.
=> Fix decorator issues with 1.5.x branch 

tobac/feature_detection.py, tobac/segmentation.py, tobac/tests/test_pbc_utils.py, tobac/tests/test_segmentation.py, tobac/tests/test_tracking.py, tobac/tracking.py, tobac/utils/periodic_boundaries.py
Following on from #384 , I've carried out a more substantial refactoring of the PBC distance calculation functions. This includes improved validation of PBC keyword parameters, and optimisation of the `calc_distance_coords_pbc` to reduce the amount of work performed each time it is called. `build_distance_function` should now be the uniform way to create a PBC dist func across all routines
Change in performance of tracking with PBCs (for a 24x1200x3600 dataset):
```
No PBCs: 4.41 s ± 445 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Pre-refactor: 52 s ± 4.26 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
Post-refactor: 23.7 s ± 570 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
=> Refactor of PBC distance functions

tobac/tests/test_utils.py
This PR addresses #425 and adds a test for the get_spacings function.
=> Added missing test for get_spacings

tobac/feature_detection.py
=> updated docstrings for n_min_threshold

tobac/tests/test_decorators.py, tobac/tests/test_utils_bulk_statistics.py, tobac/utils/bulk_statistics.py, tobac/utils/decorators.py, tobac/utils/periodic_boundaries.py
A few small fixes for the bulk statistics method `get_statistics_from_mask`: 
- At some locations the hardcoded column name "feature" was not updated with the string variable `id_column` which can be defined by the user in case one wants to use an ID with another column name to compute the bulk statistics. This caused the bulk statistics to fail when you input a dataframe that uses a different column name as the feature ID. 
- Added some test parameters in `test_utils_bulk_statistics` to account for the above case. Also added `index` here since we have not previously covered this parameter with the tests. This parameter allows users to compute bulk statistics for specified feature regions only. 
- Corrected the warning message that accidently included a `raise` statement which resulted in …
=> Bulk stats bug fix

tobac/feature_detection.py, tobac/utils/general.py
Resolves #433. Clipping of hdim1/2 values to size of dimensions (or size + 1 for periodic coordinates) in `feature_location`, and extrapolation enabled for 2d/3d coordinates as with 1d coords.
=> Fix floating point error in 2d/3d coordinate interpolation

.github/workflows/matrix_ci.yml, tobac/tests/test_segmentation.py, tobac/tests/test_utils.py, tobac/utils/general.py
Fixes a bug in `transform_feature_points` which was causing the failing matrix tests. I also fixed a couple of other depreciation warnings in the tests, and added python 3.12 to matrix testing. Resolves #444
=> Matrix testing fix

.github/workflows/matrix_ci.yml, doc/index.rst, doc/publications.rst, tobac/tests/test_segmentation.py, tobac/tests/test_utils.py, tobac/utils/general.py
Updated the reference and thereby solved #445
=> updated v1.5 reference to peer-reviewed 

.pre-commit-config.yaml, tobac/feature_detection.py, tobac/segmentation.py, tobac/tests/test_utils_bulk_statistics.py, tobac/utils/decorators.py
Addresses #440 and allows for the user to choose whether the bulk statistics in the feature detection are calculated on the unsmoothed or the smoothed input data.
=> Optional calculation of bulk statistics in feature detection on raw input (before smoothing)

tobac/feature_detection.py, tobac/tests/test_feature_detection.py
Resolves #430 and #413
The order of coordinate interpolation and minimum distance filtering has been swapped, so that the z coordinate can be used for finding the spacing of features rather than assuming a fixed vertical grid spacing. The `filter_min_distance` has also been fixed so that the provided z coordinate will be used, rather than always using `dz`. Incidentally, another bug was fixed in `feature_detection_multithreshold_timestep` was fixed, in which statistics were being recalculated at each threshold value, rather than once at the end.
Ideally, I would like to move adding coordinates and distance filtering inside `feature_detection_multithreshold_timestep`, but at the moment we are not passing through the required info to do this. As the feature detection code is in need of …
=> Fix minimum distance filtering for varying vertical coordinates

.github/workflows/check_formatting.yml, .github/workflows/check_json.yml, environment-ci.yml, tobac/feature_detection.py, tobac/tests/test_utils_bulk_statistics.py, tobac/utils/bulk_statistics.py
This addresses #453 and the zenodo JSON checks. Code is touched (due to new `black` formatting requirements), so want to make this part of 1.5.4.
=> Fix JSON and Black checks

.github/workflows/check_notebooks.yml, .github/workflows/codecov-CI.yml, .github/workflows/pylint.yml, environment-examples.yml
This continues the work from #457 and fixes issues with a few of our CI workflows that broke from `miniconda` being depreciated. 
Note that this is a _PR to main_ per our policy of CI improvements
=> Fix CI issues due to old conda version

.github/workflows/matrix_ci.yml, tobac/merge_split.py, tobac/plotting.py, tobac/segmentation.py, tobac/tests/test_tracking.py, tobac/tracking.py, tobac/utils/bulk_statistics.py, tobac/utils/decorators.py, tobac/utils/general.py
Resolves #467 . Note that the initial commit _should_ fail CI as I haven't implemented the typing fix yet (intentionally).
=> Fix Matrix Testing & Typing Error

tobac/tests/test_utils_bulk_statistics.py, tobac/utils/bulk_statistics.py
Change .data to .values call in get_statistics_from_mask to prevent passing dask array to get_statistics, and added test for dask array input
Fixes #472
=> Fix bug in bulk_statistics when providing a DataArray or iris cube with dask array data

.zenodo.json, CHANGELOG.md, doc/big_datasets_examples/notebooks/parallel_processing_tobac.ipynb, doc/bulk_statistics/notebooks/compute_statistics_during_feature_detection.ipynb, doc/bulk_statistics/notebooks/compute_statistics_during_segmentation.ipynb, doc/bulk_statistics/notebooks/compute_statistics_postprocessing_example.ipynb, doc/feature_detection/notebooks/feature_detection_filtering.ipynb, doc/feature_detection/notebooks/multiple_thresholds_example.ipynb, doc/feature_detection/notebooks/n_min_threshold_example.ipynb, doc/feature_detection/notebooks/position_threshold_example.ipynb, examples/Basics/Idealized-Case-1_Tracking-of-a-Test-Blob-in-2D.ipynb, examples/Basics/Idealized-Case-2_Two_crossing_Blobs.ipynb, examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_1.ipynb, examples/Basics/Methods-and-Parameters-for-Feature-Detection_Part_2.ipynb, examples/Basics/Methods-and-Parameters-for-Linking.ipynb, examples/Basics/Methods-and-Parameters-for-Segmentation.ipynb, examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb, examples/Example_OLR_Tracking_model_iris/Example_OLR_Tracking_model_iris.ipynb, examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb, examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb, examples/Example_Track_on_Radar_Segment_on_Satellite/Example_Track_on_Radar_Segment_on_Satellite.ipynb, examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb, examples/Example_vorticity_tracking_model/Example_vorticity_tracking_model.ipynb, tobac/__init__.py
=> Update version number, changelog and notebooks for v1.6.0 release

tobac/tests/test_xarray_utils.py, tobac/utils/internal/xarray_utils.py
Resolves the issue in #503 where feature detection would fail if there are non-numeric coordinates except for `time` (in that case, `step` and `valid_time` coordinates). This update checks for non-numeric coordinates and instead finds the nearest values rather than interpolating, in the same manner as done for time.
=> Fix coordinate interpolation bug for non-numeric dtypes
