tobac/__init__.py
tobac/analysis.py

fixes in calculation of track and feature properties (nearest neighbour distances, velocity, area) and respective histograms, added functions to __init__.py

fixes in calculation of track and feature properties and histograms

---

tobac/testing.py
tobac/tests/test_import.py
tobac/tests/test_sample_data.py

Added more complex tests based on sample data created in tobac.testing

Added more complex tests and associated functions

---

.travis.yml
conda-requirements.txt

Replaced wrong cf_units by cf-units in dependencies and some fixes to .travis.yml file

Fixed dependencies

---

.travis.yml
conda-requirements.txt

Replaced wrong cf_units by cf-units in dependencies and some fixes to .travis.yml file

Fixed dependencies (#31)

---

tobac/themes/tobac_v1/tracking.py

`linking_trackpy` uses too many loops which will cost more time for large datasets.
Detailed tests are listed in the comments ...

Speed up linking_trackpy

---

tobac/analysis.py

This should resolve #50. Ultimately, it would be good to add more tests for the analysis code to avoid these issues.

Changed call to calculate_area to fix a bug

---

.github/workflows/docker-image.yml

Added the v2.0-dev branch to our CI as discussed in the meeting Friday.

Added v2.0-dev branch to CI

---

.github/workflows/docker-image.yml
tobac/analysis.py
tobac/tests/Dockerfile

I'd like to merge `dev` with `main` so that we have the new CI via GitHub actions (#68) on the `main` branch. This will also bring in the bugfix (#66) to this branch. I don't think we need a release yet, but it would be good to get this current.

Bringing in current `dev` branch to `main` with new CI and bugfix

---

.github/workflows/docker-image.yml
tobac/testing.py
tobac/tests/test_feature_detection.py
tobac/tests/test_testing.py
tobac/tests/test_tracking.py

As part of our efforts here on speedups and 3D/PBC changes, we've also started to beef up the test cases. This PR contains several new utility functions for testing (that are generally, themselves, tested) and a simple test case for feature detection. We're planning on continuing to expand on this, producing similar tests for tracking and segmentation. For tracking, I'm waiting until #74 is resolved as there are some headaches dealing with the changing data types.

New testing utilities and feature detection tests

---

tobac/analysis/__init__.py
tobac/analysis/analysis.py
tobac/analysis/centerofgravity.py
tobac/examples/cpol_example.py
tobac/examples/eric_test.py
tobac/examples/wrf_example.py
tobac/plot/__init__.py
tobac/plot/plotting.py
tobac/testing.py
tobac/tests/test_import.py
tobac/tests/test_sample_data_tobacv1.py
tobac/tests/test_utils.py
tobac/themes/tint/grid_utils.py
tobac/themes/tint/helpers.py
tobac/themes/tint/io.py
tobac/themes/tint/matching.py
tobac/themes/tint/objects.py
tobac/themes/tint/phase_correlation.py
tobac/themes/tint/tracks.py
tobac/themes/tobac_v1/__init__.py
tobac/themes/tobac_v1/mask_segmentation.py
tobac/themes/tobac_v1/tracking.py
tobac/utils/__init__.py
tobac/utils/convert.py
tobac/utils/mask.py

Bug fix for ```spectral_filtering``` in ```utils/general.py```  that belongs to PR #65

Bug fix for spectral filtering feature

---

tobac/utils/general.py

fixed the bug that was mentioned #48

bug fix: added missing 'raise' in get_spacing to actually raise ValueError

---

tobac/utils.py

Same fix as #103 for ```dev```, issue #48 should be solved with this

added missing 'raise' in get_spacings to actually raise ValueError

---

tobac/themes/tobac_v1/feature_detection.py
tobac/utils/general.py

Support setting interpolation kind of coord.

Support interp kind

---

.github/pull_request_template.md

Added a pull request check list that automatically will appear in the pull request description field. Please feel free to add any checks that I have missed or remove redundant instructions. I have put the file here to not overpopulate the root directory. We could, however also move it to doc/

added pull_request_template.md in .github/

---

tobac/segmentation.py

Reverts tobac-project/tobac#147 until we resolve the best way to do this as discussed in #145.

Revert "Added depreciation warnings to two segmentation functions"

---

CHANGELOG.md
setup.py

Update version number and changelog in prep for 1.3.2

---

CHANGELOG.md
setup.py
tobac/tests/test_tracking.py
tobac/tracking.py

Updates from #170 for merging into Main. Only one PR in this release.
Checklist for the release is in #171.

Merging `hotfix` into `main` for v1.3.3

---

tobac/utils.py

This pull request concludes my work on the documentation of tobac with the revision of the docstrings in utils.py  for now. 
I also included fixes for two small bugs i found while testing the functions:
- Setting `mask_i_surface.data` instead of `mask_i_surface` in `mask_all_surface()`
- Comparing `mask.core_data()` instead of `mask` in `mask_cube()`
Functions that do not work atm:
`mask_cell_columns()`
Functions that I was not able to call corrrectly: 
`column_mask_from2D()`
Not needed:

Docstrings + Bugfixes for utils.py

---

tobac/feature_detection.py
tobac/tests/test_feature_detection.py

Resolves #167 and sorts thresholds in feature detection based on the target.

Sort feature detection thresholds based on target

---

README.md

Fixed downloads badge in the README.

Updating Readme to show badge correctly

---

.zenodo.json
CHANGELOG.md
tobac/__init__.py

Update documentation for v1.4.1

---

tobac/feature_detection.py
tobac/tests/test_feature_detection.py

Resolves #243, part of #230 
Changes should be covered by existing feature detection tests, however we should check that we are actually testing cases where features are located closer to each other than the distance threshold
Edit: this isn't covered by `test_filter_min_distance`, I'll look how this test works and add a target option

Add target option to `filter_min_distance`

---

doc/feature_detection/notebooks/feature_detection_filtering.ipynb

As discussed in #258 I have corrected a reference to a non-existing variable. I guess `selem` was supposed to be `footprint`. Is this correct @freemansw1?

reference to non-existing variable corrected

---

doc/code_reviews.rst

Small fixes / additions to the dev guide

---

doc/conf.py

Fixes our API docs for v1.5.0. I forgot to add `sklearn` as a dependency to mock.

Fix v1.5.0 API docs (again)

---

.github/workflows/check_notebooks.yml
.readthedocs.yml
CHANGELOG.md
doc/feature_detection/notebooks/feature_detection_filtering.ipynb
doc/feature_detection/notebooks/multiple_thresholds_example.ipynb
doc/feature_detection/notebooks/n_min_threshold_example.ipynb
doc/feature_detection/notebooks/position_threshold_example.ipynb
example_requirements.txt
examples/Example_OLR_Tracking_model/Example_OLR_Tracking_model.ipynb
examples/Example_OLR_Tracking_satellite/Example_OLR_Tracking_satellite.ipynb
examples/Example_Precip_Tracking/Example_Precip_Tracking.ipynb
examples/Example_Track_on_Radar_Segment_on_Satellite/track_on_radar_segment_on_satellite.ipynb
examples/Example_Updraft_Tracking/Example_Updraft_Tracking.ipynb
tobac/__init__.py
tobac/feature_detection.py
tobac/tests/test_feature_detection.py
tobac/tests/test_tracking.py
tobac/utils/__init__.py
tobac/utils/general.py
tobac/utils/internal.py

This is just a PR to update `RC_v1.5.x` with our updates to `main` post v1.5.1 release.

Update `RC_v1.5.x` with v1.5.1 changes from `main`

---

tobac/tests/test_tracking.py
tobac/tracking.py

Previously tracking with PBCs could fail if min/max dimension indices were not provided even if PBCs were not applied over that dimension

Fix issue with numba and PBC dist func

---

doc/bulk_statistics/index.rst
doc/index.rst
doc/tobac.rst
tobac/utils/bulk_statistics.py

Fix docs not showing all bulk statistics examples

---

.github/workflows/codecov-CI.yml

This maybe addresses #435 by updating our code coverage action to v4.

Update codecov action to v4

---

doc/conf.py
doc/tobac.rst

Fix API rendering bug due to missing `cftime` mocking the docs config. Fixes #498

Fix API rendering
